-- 結算賬戶表 (需要 tenant_id - 因為涉及資金)
CREATE TABLE IF NOT EXISTS erp_account (
    id           BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '結算賬戶編號',
    name         VARCHAR(100) NOT NULL COMMENT '賬戶名稱',
    no           VARCHAR(50)  NOT NULL COMMENT '賬戶編碼',
    remark       VARCHAR(500) COMMENT '備註',
    status       TINYINT     NOT NULL COMMENT '開啟狀態',
    sort         INT         NOT NULL DEFAULT 0 COMMENT '排序',
    default_status BOOLEAN   NOT NULL DEFAULT FALSE COMMENT '是否默認',
    creator      VARCHAR(64) NOT NULL DEFAULT '' COMMENT '創建者',
    create_time  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater      VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新者',
    update_time  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted      BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id    BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    UNIQUE KEY uk_no_tenant (no, tenant_id, deleted),
    KEY idx_status_sort (status, sort, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '結算賬戶';

-- 產品單位表 (無需 tenant_id - 通用基礎數據)
CREATE TABLE IF NOT EXISTS erp_product_unit (
    id          BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '單位編號',
    name        VARCHAR(100) NOT NULL COMMENT '單位名稱',
    status      TINYINT     NOT NULL COMMENT '單位狀態',
    creator     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    UNIQUE KEY uk_name (name, deleted),
    KEY idx_status (status, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '產品單位';

-- 產品分類表 (需要 tenant_id - 不同租戶有不同分類體系)
CREATE TABLE IF NOT EXISTS erp_product_category (
    id          BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '分類編號',
    parent_id   BIGINT      NOT NULL DEFAULT 0 COMMENT '父分類編號',
    name        VARCHAR(100) NOT NULL COMMENT '分類名稱',
    code        VARCHAR(50)  NOT NULL COMMENT '分類編碼',
    sort        INT         NOT NULL DEFAULT 0 COMMENT '分類排序',
    status      TINYINT     NOT NULL COMMENT '開啟狀態',
    creator     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id   BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    UNIQUE KEY uk_code_tenant (code, tenant_id, deleted),
    KEY idx_parent_sort (parent_id, sort, tenant_id, deleted),
    KEY idx_status (status, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '產品分類';

-- 產品表 (需要 tenant_id - 核心業務數據)
CREATE TABLE IF NOT EXISTS erp_product (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '產品編號',
    name            VARCHAR(200) NOT NULL COMMENT '產品名稱',
    bar_code        VARCHAR(50)  NOT NULL COMMENT '產品條碼',
    category_id     BIGINT      NOT NULL COMMENT '產品分類編號',
    unit_id         BIGINT      NOT NULL COMMENT '單位編號',
    status          TINYINT     NOT NULL COMMENT '產品狀態',
    standard        VARCHAR(100) COMMENT '產品規格',
    remark          VARCHAR(500) COMMENT '產品備註',
    expiry_day      INT COMMENT '保質期天數',
    weight          DECIMAL(10,2) COMMENT '基礎重量(kg)',
    purchase_price  DECIMAL(10,2) NOT NULL COMMENT '採購價格',
    sale_price      DECIMAL(10,2) NOT NULL COMMENT '銷售價格',
    min_price       DECIMAL(10,2) NOT NULL COMMENT '最低價格',
    creator         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id       BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    UNIQUE KEY uk_bar_code_tenant (bar_code, tenant_id, deleted),
    KEY idx_category (category_id, tenant_id, deleted),
    KEY idx_status (status, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '產品';

-- 收款單表 (需要 tenant_id - 涉及資金)
CREATE TABLE IF NOT EXISTS erp_finance_receipt (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '編號',
    no              VARCHAR(50)  NOT NULL COMMENT '收款單號',
    status          TINYINT     NOT NULL COMMENT '收款狀態',
    receipt_time    DATETIME    NOT NULL COMMENT '收款時間',
    finance_user_id BIGINT      NOT NULL COMMENT '財務人員編號',
    customer_id     BIGINT      NOT NULL COMMENT '客戶編號',
    account_id      BIGINT      NOT NULL COMMENT '收款賬戶編號',
    total_price     DECIMAL(10,2) NOT NULL COMMENT '合計價格',
    discount_price  DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '優惠金額',
    receipt_price   DECIMAL(10,2) NOT NULL COMMENT '實付金額',
    remark          VARCHAR(500) COMMENT '備註',
    creator         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id       BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    UNIQUE KEY uk_no_tenant (no, tenant_id, deleted),
    KEY idx_receipt_time (receipt_time, tenant_id, deleted),
    KEY idx_customer (customer_id, tenant_id, deleted),
    KEY idx_status (status, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '收款單';

-- 收款項表 (需要 tenant_id - 關聯收款單)
CREATE TABLE IF NOT EXISTS erp_finance_receipt_item (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '收款項編號',
    receipt_id      BIGINT      NOT NULL COMMENT '收款單編號',
    biz_type        TINYINT     NOT NULL COMMENT '業務類型',
    biz_id          BIGINT      NOT NULL COMMENT '業務編號',
    biz_no          VARCHAR(50) NOT NULL COMMENT '業務單號',
    total_price     DECIMAL(10,2) NOT NULL COMMENT '應收金額',
    receipted_price DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '已收金額',
    receipt_price   DECIMAL(10,2) NOT NULL COMMENT '本次收款',
    remark          VARCHAR(500) COMMENT '備註',
    creator         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id       BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    KEY idx_receipt_tenant (receipt_id, tenant_id, deleted),
    KEY idx_biz_tenant (biz_type, biz_id, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '收款項';

-- 付款單表 (需要 tenant_id - 涉及資金)
CREATE TABLE IF NOT EXISTS erp_finance_payment (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '編號',
    no              VARCHAR(50)  NOT NULL COMMENT '付款單號',
    status          TINYINT     NOT NULL COMMENT '付款狀態',
    payment_time    DATETIME    NOT NULL COMMENT '付款時間',
    finance_user_id BIGINT      NOT NULL COMMENT '財務人員編號',
    supplier_id     BIGINT      NOT NULL COMMENT '供應商編號',
    account_id      BIGINT      NOT NULL COMMENT '付款賬戶編號',
    total_price     DECIMAL(10,2) NOT NULL COMMENT '合計價格',
    discount_price  DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '優惠金額',
    payment_price   DECIMAL(10,2) NOT NULL COMMENT '實付金額',
    remark          VARCHAR(500) COMMENT '備註',
    creator         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id       BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    UNIQUE KEY uk_no_tenant (no, tenant_id, deleted),
    KEY idx_payment_time (payment_time, tenant_id, deleted),
    KEY idx_supplier (supplier_id, tenant_id, deleted),
    KEY idx_status (status, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '付款單';

-- 付款項表 (需要 tenant_id - 關聯付款單)
CREATE TABLE IF NOT EXISTS erp_finance_payment_item (
    id              BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '付款項編號',
    payment_id      BIGINT      NOT NULL COMMENT '付款單編號',
    biz_type        TINYINT     NOT NULL COMMENT '業務類型',
    biz_id          BIGINT      NOT NULL COMMENT '業務編號',
    biz_no          VARCHAR(50) NOT NULL COMMENT '業務單號',
    total_price     DECIMAL(10,2) NOT NULL COMMENT '應付金額',
    paid_price      DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '已付金額',
    payment_price   DECIMAL(10,2) NOT NULL COMMENT '本次付款',
    remark          VARCHAR(500) COMMENT '備註',
    creator         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id       BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    KEY idx_payment_tenant (payment_id, tenant_id, deleted),
    KEY idx_biz_tenant (biz_type, biz_id, tenant_id, deleted)
) ENGINE = InnoDB COMMENT '付款項';

-- 供應商表 (需要 tenant_id - 重要主數據)
CREATE TABLE IF NOT EXISTS erp_supplier (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '供應商編號',
    name         VARCHAR(100) NOT NULL COMMENT '供應商名稱',
    contact      VARCHAR(50) COMMENT '聯系人',
    mobile       VARCHAR(20) COMMENT '手機號碼',
    telephone    VARCHAR(20) COMMENT '聯系電話',
    email        VARCHAR(100) COMMENT '電子郵箱',
    fax          VARCHAR(20) COMMENT '傳真',
    remark       VARCHAR(500) COMMENT '備註',
    status       TINYINT NOT NULL COMMENT '開啟狀態',
    sort         INT COMMENT '排序',
    tax_no       VARCHAR(50) COMMENT '納稅人識別號',
    tax_percent  DECIMAL(8,2) COMMENT '稅率',
    bank_name    VARCHAR(100) COMMENT '開戶行',
    bank_account VARCHAR(100) COMMENT '開戶賬號',
    bank_address VARCHAR(200) COMMENT '開戶地址',
    creator      VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater      VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted      TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id    BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_status_deleted (deleted, status, tenant_id),
    KEY idx_name (name, tenant_id)
) COMMENT '供應商表';

-- 採購訂單表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_purchase_order (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    no                  VARCHAR(50) NOT NULL COMMENT '採購訂單號',
    status             TINYINT NOT NULL COMMENT '採購狀態',
    supplier_id         BIGINT NOT NULL COMMENT '供應商編號',
    account_id         BIGINT NOT NULL COMMENT '結算賬戶編號',
    order_time         DATETIME NOT NULL COMMENT '下單時間',
    total_count        DECIMAL(10,2) NOT NULL COMMENT '合計數量',
    total_price        DECIMAL(10,2) NOT NULL COMMENT '最終合計價格',
    total_product_price DECIMAL(10,2) NOT NULL COMMENT '合計產品價格',
    total_tax_price    DECIMAL(10,2) NOT NULL COMMENT '合計稅額',
    discount_percent   DECIMAL(8,2) COMMENT '優惠率',
    discount_price     DECIMAL(10,2) COMMENT '優惠金額',
    deposit_price      DECIMAL(10,2) COMMENT '定金金額',
    in_count          DECIMAL(10,2) DEFAULT 0 COMMENT '採購入庫數量',
    return_count      DECIMAL(10,2) DEFAULT 0 COMMENT '採購退貨數量',
    file_url          VARCHAR(500) COMMENT '附件地址',
    remark            VARCHAR(500) COMMENT '備註',
    creator           VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater           VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted           TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id         BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id),
    KEY idx_status_deleted (deleted, status, tenant_id),
    KEY idx_supplier_tenant (supplier_id, tenant_id),
    KEY idx_order_time_tenant (order_time, tenant_id)
) COMMENT '採購訂單表';

-- 採購訂單項表 (需要 tenant_id - 關聯採購訂單)
CREATE TABLE IF NOT EXISTS erp_purchase_order_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    order_id         BIGINT NOT NULL COMMENT '採購訂單編號',
    product_id       BIGINT NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT NOT NULL COMMENT '產品單位',
    product_price    DECIMAL(10,2) NOT NULL COMMENT '產品單價',
    count            DECIMAL(10,2) NOT NULL COMMENT '數量',
    total_price      DECIMAL(10,2) NOT NULL COMMENT '總價',
    tax_percent      DECIMAL(8,2) COMMENT '稅率',
    tax_price        DECIMAL(10,2) COMMENT '稅額',
    in_count         DECIMAL(10,2) DEFAULT 0 COMMENT '採購入庫數量',
    return_count     DECIMAL(10,2) DEFAULT 0 COMMENT '採購退貨數量',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id        BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_order_deleted_tenant (deleted, order_id, tenant_id),
    KEY idx_product_tenant (product_id, tenant_id)
) COMMENT '採購訂單項表';

-- 採購入庫表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_purchase_in (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    no                  VARCHAR(50) NOT NULL COMMENT '採購入庫單號',
    status              TINYINT NOT NULL COMMENT '入庫狀態',
    supplier_id         BIGINT NOT NULL COMMENT '供應商編號',
    account_id          BIGINT NOT NULL COMMENT '結算賬戶編號',
    in_time             DATETIME NOT NULL COMMENT '入庫時間',
    order_id            BIGINT COMMENT '採購訂單編號',
    order_no            VARCHAR(50) COMMENT '採購訂單號',
    total_count         DECIMAL(10,2) NOT NULL COMMENT '合計數量',
    total_price         DECIMAL(10,2) NOT NULL COMMENT '最終合計價格',
    total_product_price DECIMAL(10,2) NOT NULL COMMENT '合計產品價格',
    total_tax_price     DECIMAL(10,2) NOT NULL COMMENT '合計稅額',
    discount_percent    DECIMAL(8,2) COMMENT '優惠率',
    discount_price      DECIMAL(10,2) COMMENT '優惠金額',
    other_price         DECIMAL(10,2) COMMENT '其它金額',
    payment_price       DECIMAL(10,2) DEFAULT 0 COMMENT '已支付金額',
    file_url           VARCHAR(500) COMMENT '附件地址',
    remark             VARCHAR(500) COMMENT '備註',
    creator            VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater            VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted            TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id          BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id),
    KEY idx_status_deleted_tenant (deleted, status, tenant_id),
    KEY idx_supplier_tenant (supplier_id, tenant_id),
    KEY idx_order_tenant (order_id, tenant_id),
    KEY idx_in_time_tenant (in_time, tenant_id)
) COMMENT '採購入庫表';

-- 採購入庫項表 (需要 tenant_id - 關聯採購入庫單)
CREATE TABLE IF NOT EXISTS erp_purchase_in_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    in_id            BIGINT NOT NULL COMMENT '採購入庫編號',
    order_item_id    BIGINT COMMENT '採購訂單項編號',
    warehouse_id     BIGINT NOT NULL COMMENT '倉庫編號',
    product_id       BIGINT NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT NOT NULL COMMENT '產品單位',
    product_price    DECIMAL(10,2) NOT NULL COMMENT '產品單價',
    count            DECIMAL(10,2) NOT NULL COMMENT '數量',
    total_price      DECIMAL(10,2) NOT NULL COMMENT '總價',
    tax_percent      DECIMAL(8,2) COMMENT '稅率',
    tax_price        DECIMAL(10,2) COMMENT '稅額',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id        BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_in_deleted_tenant (deleted, in_id, tenant_id),
    KEY idx_order_item_tenant (order_item_id, tenant_id),
    KEY idx_warehouse_tenant (warehouse_id, tenant_id),
    KEY idx_product_tenant (product_id, tenant_id)
) COMMENT '採購入庫項表';

-- 採購退貨表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_purchase_return (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    no                  VARCHAR(50) NOT NULL COMMENT '採購退貨單號',
    status              TINYINT NOT NULL COMMENT '退貨狀態',
    supplier_id         BIGINT NOT NULL COMMENT '供應商編號',
    account_id          BIGINT NOT NULL COMMENT '結算賬戶編號',
    return_time         DATETIME NOT NULL COMMENT '退貨時間',
    order_id            BIGINT COMMENT '採購訂單編號',
    order_no            VARCHAR(50) COMMENT '採購訂單號',
    total_count         DECIMAL(10,2) NOT NULL COMMENT '合計數量',
    total_price         DECIMAL(10,2) NOT NULL COMMENT '最終合計價格',
    total_product_price DECIMAL(10,2) NOT NULL COMMENT '合計產品價格',
    total_tax_price     DECIMAL(10,2) NOT NULL COMMENT '合計稅額',
    discount_percent    DECIMAL(8,2) COMMENT '優惠率',
    discount_price      DECIMAL(10,2) COMMENT '優惠金額',
    other_price         DECIMAL(10,2) COMMENT '其它金額',
    refund_price        DECIMAL(10,2) DEFAULT 0 COMMENT '已退款金額',
    file_url           VARCHAR(500) COMMENT '附件地址',
    remark             VARCHAR(500) COMMENT '備註',
    creator            VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater            VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted            TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id          BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id),
    KEY idx_status_deleted_tenant (deleted, status, tenant_id),
    KEY idx_supplier_tenant (supplier_id, tenant_id),
    KEY idx_order_tenant (order_id, tenant_id),
    KEY idx_return_time_tenant (return_time, tenant_id)
) COMMENT '採購退貨表';

-- 採購退貨項表 (需要 tenant_id - 關聯採購退貨單)
CREATE TABLE IF NOT EXISTS erp_purchase_return_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    return_id        BIGINT NOT NULL COMMENT '採購退貨編號',
    order_item_id    BIGINT COMMENT '採購訂單項編號',
    warehouse_id     BIGINT NOT NULL COMMENT '倉庫編號',
    product_id       BIGINT NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT NOT NULL COMMENT '產品單位',
    product_price    DECIMAL(10,2) NOT NULL COMMENT '產品單價',
    count            DECIMAL(10,2) NOT NULL COMMENT '數量',
    total_price      DECIMAL(10,2) NOT NULL COMMENT '總價',
    tax_percent      DECIMAL(8,2) COMMENT '稅率',
    tax_price        DECIMAL(10,2) COMMENT '稅額',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id        BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_return_deleted_tenant (deleted, return_id, tenant_id),
    KEY idx_order_item_tenant (order_item_id, tenant_id),
    KEY idx_warehouse_tenant (warehouse_id, tenant_id),
    KEY idx_product_tenant (product_id, tenant_id)
) COMMENT '採購退貨項表';

-- 客戶表 (需要 tenant_id - 重要主數據)
CREATE TABLE IF NOT EXISTS erp_customer (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '客戶編號',
    name         VARCHAR(100) NOT NULL COMMENT '客戶名稱',
    contact      VARCHAR(50) COMMENT '聯系人',
    mobile       VARCHAR(20) COMMENT '手機號碼',
    telephone    VARCHAR(20) COMMENT '聯系電話',
    email        VARCHAR(100) COMMENT '電子郵箱',
    fax          VARCHAR(20) COMMENT '傳真',
    remark       VARCHAR(500) COMMENT '備註',
    status       TINYINT NOT NULL COMMENT '開啟狀態',
    sort         INT COMMENT '排序',
    tax_no       VARCHAR(50) COMMENT '納稅人識別號',
    tax_percent  DECIMAL(8,2) COMMENT '稅率',
    bank_name    VARCHAR(100) COMMENT '開戶行',
    bank_account VARCHAR(100) COMMENT '開戶賬號',
    bank_address VARCHAR(200) COMMENT '開戶地址',
    creator      VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater      VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted      TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id    BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_status_deleted_tenant (deleted, status, tenant_id),
    KEY idx_name_tenant (name, tenant_id)
) COMMENT '客戶表';

-- 銷售訂單表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_sale_order (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    no                  VARCHAR(50) NOT NULL COMMENT '銷售訂單號',
    status              TINYINT NOT NULL COMMENT '銷售狀態',
    customer_id         BIGINT NOT NULL COMMENT '客戶編號',
    account_id          BIGINT NOT NULL COMMENT '結算賬戶編號',
    sale_user_id        BIGINT NOT NULL COMMENT '銷售員編號',
    order_time          DATETIME NOT NULL COMMENT '下單時間',
    total_count         DECIMAL(10,2) NOT NULL COMMENT '合計數量',
    total_price         DECIMAL(10,2) NOT NULL COMMENT '最終合計價格',
    total_product_price DECIMAL(10,2) NOT NULL COMMENT '合計產品價格',
    total_tax_price     DECIMAL(10,2) NOT NULL COMMENT '合計稅額',
    discount_percent    DECIMAL(8,2) COMMENT '優惠率',
    discount_price      DECIMAL(10,2) COMMENT '優惠金額',
    deposit_price       DECIMAL(10,2) COMMENT '定金金額',
    out_count           DECIMAL(10,2) DEFAULT 0 COMMENT '銷售出庫數量',
    return_count        DECIMAL(10,2) DEFAULT 0 COMMENT '銷售退貨數量',
    file_url           VARCHAR(500) COMMENT '附件地址',
    remark             VARCHAR(500) COMMENT '備註',
    creator            VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater            VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted            TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id          BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id),
    KEY idx_status_deleted_tenant (deleted, status, tenant_id),
    KEY idx_customer_tenant (customer_id, tenant_id),
    KEY idx_sale_user_tenant (sale_user_id, tenant_id),
    KEY idx_order_time_tenant (order_time, tenant_id)
) COMMENT '銷售訂單表';

-- 銷售訂單項表 (需要 tenant_id - 關聯銷售訂單)
CREATE TABLE IF NOT EXISTS erp_sale_order_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    order_id         BIGINT NOT NULL COMMENT '銷售訂單編號',
    product_id       BIGINT NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT NOT NULL COMMENT '產品單位',
    product_price    DECIMAL(10,2) NOT NULL COMMENT '產品單價',
    count            DECIMAL(10,2) NOT NULL COMMENT '數量',
    total_price      DECIMAL(10,2) NOT NULL COMMENT '總價',
    tax_percent      DECIMAL(8,2) COMMENT '稅率',
    tax_price        DECIMAL(10,2) COMMENT '稅額',
    out_count        DECIMAL(10,2) DEFAULT 0 COMMENT '銷售出庫數量',
    return_count     DECIMAL(10,2) DEFAULT 0 COMMENT '銷售退貨數量',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id        BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_order_deleted_tenant (deleted, order_id, tenant_id),
    KEY idx_product_tenant (product_id, tenant_id)
) COMMENT '銷售訂單項表';

-- 銷售出庫表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_sale_out (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    no                  VARCHAR(50) NOT NULL COMMENT '銷售出庫單號',
    status              TINYINT NOT NULL COMMENT '出庫狀態',
    customer_id         BIGINT NOT NULL COMMENT '客戶編號',
    account_id          BIGINT NOT NULL COMMENT '結算賬戶編號',
    sale_user_id        BIGINT NOT NULL COMMENT '銷售員編號',
    out_time            DATETIME NOT NULL COMMENT '出庫時間',
    order_id            BIGINT COMMENT '銷售訂單編號',
    order_no            VARCHAR(50) COMMENT '銷售訂單號',
    total_count         DECIMAL(10,2) NOT NULL COMMENT '合計數量',
    total_price         DECIMAL(10,2) NOT NULL COMMENT '最終合計價格',
    total_product_price DECIMAL(10,2) NOT NULL COMMENT '合計產品價格',
    total_tax_price     DECIMAL(10,2) NOT NULL COMMENT '合計稅額',
    discount_percent    DECIMAL(8,2) COMMENT '優惠率',
    discount_price      DECIMAL(10,2) COMMENT '優惠金額',
    other_price         DECIMAL(10,2) COMMENT '其它金額',
    receipt_price       DECIMAL(10,2) DEFAULT 0 COMMENT '已收款金額',
    file_url           VARCHAR(500) COMMENT '附件地址',
    remark             VARCHAR(500) COMMENT '備註',
    creator            VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater            VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted            TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id          BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id),
    KEY idx_status_deleted_tenant (deleted, status, tenant_id),
    KEY idx_customer_tenant (customer_id, tenant_id),
    KEY idx_sale_user_tenant (sale_user_id, tenant_id),
    KEY idx_order_tenant (order_id, tenant_id),
    KEY idx_out_time_tenant (out_time, tenant_id)
) COMMENT '銷售出庫表';

-- 銷售出庫項表 (需要 tenant_id - 關聯銷售出庫單)
CREATE TABLE IF NOT EXISTS erp_sale_out_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    out_id           BIGINT NOT NULL COMMENT '銷售出庫編號',
    order_item_id    BIGINT COMMENT '銷售訂單項編號',
    warehouse_id     BIGINT NOT NULL COMMENT '倉庫編號',
    product_id       BIGINT NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT NOT NULL COMMENT '產品單位',
    product_price    DECIMAL(10,2) NOT NULL COMMENT '產品單價',
    count            DECIMAL(10,2) NOT NULL COMMENT '數量',
    total_price      DECIMAL(10,2) NOT NULL COMMENT '總價',
    tax_percent      DECIMAL(8,2) COMMENT '稅率',
    tax_price        DECIMAL(10,2) COMMENT '稅額',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id        BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_out_deleted_tenant (deleted, out_id, tenant_id),
    KEY idx_order_item_tenant (order_item_id, tenant_id),
    KEY idx_warehouse_tenant (warehouse_id, tenant_id),
    KEY idx_product_tenant (product_id, tenant_id)
) COMMENT '銷售出庫項表';

-- 銷售退貨表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_sale_return (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    no                  VARCHAR(50) NOT NULL COMMENT '銷售退貨單號',
    status              TINYINT NOT NULL COMMENT '退貨狀態',
    customer_id         BIGINT NOT NULL COMMENT '客戶編號',
    account_id          BIGINT NOT NULL COMMENT '結算賬戶編號',
    sale_user_id        BIGINT NOT NULL COMMENT '銷售員編號',
    return_time         DATETIME NOT NULL COMMENT '退貨時間',
    order_id            BIGINT COMMENT '銷售訂單編號',
    order_no            VARCHAR(50) COMMENT '銷售訂單號',
    total_count         DECIMAL(10,2) NOT NULL COMMENT '合計數量',
    total_price         DECIMAL(10,2) NOT NULL COMMENT '最終合計價格',
    total_product_price DECIMAL(10,2) NOT NULL COMMENT '合計產品價格',
    total_tax_price     DECIMAL(10,2) NOT NULL COMMENT '合計稅額',
    discount_percent    DECIMAL(8,2) COMMENT '優惠率',
    discount_price      DECIMAL(10,2) COMMENT '優惠金額',
    other_price         DECIMAL(10,2) COMMENT '其它金額',
    refund_price        DECIMAL(10,2) DEFAULT 0 COMMENT '已退款金額',
    file_url           VARCHAR(500) COMMENT '附件地址',
    remark             VARCHAR(500) COMMENT '備註',
    creator            VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater            VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted            TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id          BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id),
    KEY idx_status_deleted_tenant (deleted, status, tenant_id),
    KEY idx_customer_tenant (customer_id, tenant_id),
    KEY idx_sale_user_tenant (sale_user_id, tenant_id),
    KEY idx_order_tenant (order_id, tenant_id),
    KEY idx_return_time_tenant (return_time, tenant_id)
) COMMENT '銷售退貨表';

-- 銷售退貨項表 (需要 tenant_id - 關聯銷售退貨單)
CREATE TABLE IF NOT EXISTS erp_sale_return_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '編號',
    return_id        BIGINT NOT NULL COMMENT '銷售退貨編號',
    order_item_id    BIGINT COMMENT '銷售訂單項編號',
    warehouse_id     BIGINT NOT NULL COMMENT '倉庫編號',
    product_id       BIGINT NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT NOT NULL COMMENT '產品單位',
    product_price    DECIMAL(10,2) NOT NULL COMMENT '產品單價',
    count            DECIMAL(10,2) NOT NULL COMMENT '數量',
    total_price      DECIMAL(10,2) NOT NULL COMMENT '總價',
    tax_percent      DECIMAL(8,2) COMMENT '稅率',
    tax_price        DECIMAL(10,2) COMMENT '稅額',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64) DEFAULT '' COMMENT '創建者',
    create_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          TINYINT NOT NULL DEFAULT 0 COMMENT '是否刪除',
    tenant_id        BIGINT NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_return_deleted_tenant (deleted, return_id, tenant_id),
    KEY idx_order_item_tenant (order_item_id, tenant_id),
    KEY idx_warehouse_tenant (warehouse_id, tenant_id),
    KEY idx_product_tenant (product_id, tenant_id)
) COMMENT '銷售退貨項表';

-- 庫存盤點表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_stock_check (
    id           BIGINT       NOT NULL AUTO_INCREMENT COMMENT '盤點編號',
    no           VARCHAR(64)  NOT NULL COMMENT '盤點單號',
    check_time   DATETIME    NOT NULL COMMENT '盤點時間',
    total_count  DECIMAL(10, 2) NOT NULL COMMENT '合計數量',
    total_price  DECIMAL(10, 2) NOT NULL COMMENT '合計金額',
    status       TINYINT     NOT NULL COMMENT '狀態',
    remark       VARCHAR(500) COMMENT '備註',
    file_url     VARCHAR(500) COMMENT '附件URL',
    creator      VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    updater      VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    deleted      BIT         NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    create_time  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    update_time  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    tenant_id    BIGINT      NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id, deleted),
    KEY idx_status_time_tenant (status, check_time, tenant_id, deleted)
) COMMENT '庫存盤點表';

-- 庫存盤點項表 (需要 tenant_id - 關聯庫存盤點單)
CREATE TABLE IF NOT EXISTS erp_stock_check_item (
    id               BIGINT      NOT NULL AUTO_INCREMENT COMMENT '盤點項編號',
    check_id         BIGINT      NOT NULL COMMENT '盤點編號',
    warehouse_id     BIGINT      NOT NULL COMMENT '倉庫編號',
    product_id       BIGINT      NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT      NOT NULL COMMENT '產品單位編號',
    product_price    DECIMAL(10, 2) NOT NULL COMMENT '產品單價',
    stock_count      DECIMAL(10, 2) NOT NULL COMMENT '賬面數量',
    actual_count     DECIMAL(10, 2) NOT NULL COMMENT '實際數量',
    count            DECIMAL(10, 2) NOT NULL COMMENT '盈虧數量',
    total_price      DECIMAL(10, 2) NOT NULL COMMENT '合計金額',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    updater          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    deleted          BIT          NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    create_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    update_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_check_tenant (check_id, tenant_id, deleted),
    KEY idx_warehouse_product_tenant (warehouse_id, product_id, tenant_id, deleted)
) COMMENT '庫存盤點項表';

-- 產品庫存表 (需要 tenant_id - 重要數據表)
CREATE TABLE IF NOT EXISTS erp_stock (
    id               BIGINT      NOT NULL AUTO_INCREMENT COMMENT '編號',
    product_id       BIGINT      NOT NULL COMMENT '產品編號',
    warehouse_id     BIGINT      NOT NULL COMMENT '倉庫編號',
    count            DECIMAL(10, 2) NOT NULL COMMENT '庫存數量',
    creator          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    updater          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    deleted          BIT          NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    create_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    update_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_warehouse_product_tenant (warehouse_id, product_id, tenant_id, deleted)
) COMMENT '產品庫存表';

-- 其它入庫單表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_stock_in (
    id               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '入庫編號',
    no               VARCHAR(64)  NOT NULL COMMENT '入庫單號',
    supplier_id      BIGINT       NOT NULL COMMENT '供應商編號',
    in_time          DATETIME     NOT NULL COMMENT '入庫時間',
    total_count      DECIMAL(10, 2) NOT NULL COMMENT '合計數量',
    total_price      DECIMAL(10, 2) NOT NULL COMMENT '合計金額',
    status           TINYINT      NOT NULL COMMENT '狀態',
    remark           VARCHAR(500) COMMENT '備註',
    file_url         VARCHAR(500) COMMENT '附件URL',
    creator          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    updater          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    deleted          BIT          NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    create_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    update_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id, deleted),
    KEY idx_supplier_tenant (supplier_id, tenant_id, deleted),
    KEY idx_status_time_tenant (status, in_time, tenant_id, deleted)
) COMMENT '其它入庫單表';

-- 其它入庫單項表 (需要 tenant_id - 關聯其它入庫單)
CREATE TABLE IF NOT EXISTS erp_stock_in_item (
    id               BIGINT      NOT NULL AUTO_INCREMENT COMMENT '入庫項編號',
    in_id            BIGINT      NOT NULL COMMENT '入庫編號',
    warehouse_id     BIGINT      NOT NULL COMMENT '倉庫編號',
    product_id       BIGINT      NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT      NOT NULL COMMENT '產品單位編號',
    product_price    DECIMAL(10, 2) NOT NULL COMMENT '產品單價',
    count            DECIMAL(10, 2) NOT NULL COMMENT '產品數量',
    total_price      DECIMAL(10, 2) NOT NULL COMMENT '合計金額',
    remark           VARCHAR(500) COMMENT '備註',
    creator          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    updater          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    deleted          BIT          NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    create_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    update_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_in_tenant (in_id, tenant_id, deleted),
    KEY idx_warehouse_product_tenant (warehouse_id, product_id, tenant_id, deleted)
) COMMENT '其它入庫單項表';

-- 倉庫表 (需要 tenant_id - 重要主數據)
CREATE TABLE IF NOT EXISTS erp_warehouse (
    id               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '倉庫編號',
    name             VARCHAR(100) NOT NULL COMMENT '倉庫名稱',
    address          VARCHAR(200) DEFAULT NULL COMMENT '倉庫地址',
    sort             BIGINT       NOT NULL DEFAULT 0 COMMENT '排序',
    remark           VARCHAR(500) DEFAULT NULL COMMENT '備註',
    principal        VARCHAR(50)  DEFAULT NULL COMMENT '負責人',
    warehouse_price  DECIMAL(10, 2) DEFAULT 0 COMMENT '倉儲費，單位：元',
    truckage_price   DECIMAL(10, 2) DEFAULT 0 COMMENT '搬運費，單位：元',
    status           TINYINT      NOT NULL DEFAULT 0 COMMENT '開啟狀態',
    default_status   BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '是否默認',
    creator          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_status_tenant (status, deleted, tenant_id) COMMENT '狀態和租戶編號聯合索引'
) COMMENT '倉庫表';

-- 庫存調撥單表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_stock_move (
    id              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '調撥編號',
    no              VARCHAR(50)  NOT NULL COMMENT '調撥單號',
    move_time       DATETIME     NOT NULL COMMENT '調撥時間',
    total_count     DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '合計數量',
    total_price     DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '合計金額，單位：元',
    status          TINYINT      NOT NULL DEFAULT 0 COMMENT '狀態',
    remark          VARCHAR(500) DEFAULT NULL COMMENT '備註',
    file_url        VARCHAR(500) DEFAULT NULL COMMENT '附件URL',
    creator         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id       BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id, deleted) COMMENT '單號租戶唯一索引',
    KEY idx_move_time_tenant (move_time, tenant_id, deleted) COMMENT '調撥時間租戶索引',
    KEY idx_status_tenant (status, tenant_id, deleted) COMMENT '狀態租戶索引'
) COMMENT '庫存調撥單表';

-- 庫存調撥單項表 (需要 tenant_id - 關聯調撥單)
CREATE TABLE IF NOT EXISTS erp_stock_move_item (
    id                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '調撥項編號',
    move_id           BIGINT       NOT NULL COMMENT '調撥編號',
    from_warehouse_id BIGINT       NOT NULL COMMENT '調出倉庫編號',
    to_warehouse_id   BIGINT       NOT NULL COMMENT '調入倉庫編號',
    product_id        BIGINT       NOT NULL COMMENT '產品編號',
    product_unit_id   BIGINT       NOT NULL COMMENT '產品單位編號',
    product_price     DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '產品單價',
    count             DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '產品數量',
    total_price       DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '合計金額，單位：元',
    remark            VARCHAR(500) DEFAULT NULL COMMENT '備註',
    creator           VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater           VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id         BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_move_tenant (move_id, tenant_id, deleted) COMMENT '調撥單租戶索引',
    KEY idx_warehouses_tenant (from_warehouse_id, to_warehouse_id, tenant_id, deleted) COMMENT '倉庫租戶索引',
    KEY idx_product_tenant (product_id, tenant_id, deleted) COMMENT '產品租戶索引'
) COMMENT '庫存調撥單項表';

-- 其它出庫單表 (需要 tenant_id - 核心業務單據)
CREATE TABLE IF NOT EXISTS erp_stock_out (
    id              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '出庫編號',
    no              VARCHAR(50)  NOT NULL COMMENT '出庫單號',
    customer_id     BIGINT       DEFAULT NULL COMMENT '客戶編號',
    out_time        DATETIME     NOT NULL COMMENT '出庫時間',
    total_count     DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '合計數量',
    total_price     DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '合計金額，單位：元',
    status          TINYINT      NOT NULL DEFAULT 0 COMMENT '狀態',
    remark          VARCHAR(500) DEFAULT NULL COMMENT '備註',
    file_url        VARCHAR(500) DEFAULT NULL COMMENT '附件URL',
    creator         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater         VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id       BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    UNIQUE KEY uk_no_tenant (no, tenant_id, deleted) COMMENT '單號租戶唯一索引',
    KEY idx_customer_tenant (customer_id, tenant_id, deleted) COMMENT '客戶租戶索引',
    KEY idx_out_time_tenant (out_time, tenant_id, deleted) COMMENT '出庫時間租戶索引',
    KEY idx_status_tenant (status, tenant_id, deleted) COMMENT '狀態租戶索引'
) COMMENT '其它出庫單表';

-- 其它出庫單項表 (需要 tenant_id - 關聯出庫單)
CREATE TABLE IF NOT EXISTS erp_stock_out_item (
    id               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '出庫項編號',
    out_id           BIGINT       NOT NULL COMMENT '出庫編號',
    warehouse_id     BIGINT       NOT NULL COMMENT '倉庫編號',
    product_id       BIGINT       NOT NULL COMMENT '產品編號',
    product_unit_id  BIGINT       NOT NULL COMMENT '產品單位編號',
    product_price    DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '產品單價',
    count            DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '產品數量',
    total_price      DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '合計金額，單位：元',
    remark           VARCHAR(500) DEFAULT NULL COMMENT '備註',
    creator          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_out_tenant (out_id, tenant_id, deleted) COMMENT '出庫單租戶索引',
    KEY idx_warehouse_tenant (warehouse_id, tenant_id, deleted) COMMENT '倉庫租戶索引',
    KEY idx_product_tenant (product_id, tenant_id, deleted) COMMENT '產品租戶索引'
) COMMENT '其它出庫單項表';

-- 產品庫存明細表 (需要 tenant_id - 重要數據表)
CREATE TABLE IF NOT EXISTS erp_stock_record (
    id               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '編號',
    product_id       BIGINT       NOT NULL COMMENT '產品編號',
    warehouse_id     BIGINT       NOT NULL COMMENT '倉庫編號',
    count            DECIMAL(10, 2) NOT NULL COMMENT '出入庫數量',
    total_count      DECIMAL(10, 2) NOT NULL COMMENT '總庫存量',
    biz_type         TINYINT      NOT NULL COMMENT '業務類型',
    biz_id           BIGINT       NOT NULL COMMENT '業務編號',
    biz_item_id      BIGINT       NOT NULL COMMENT '業務項編號',
    biz_no           VARCHAR(50)  NOT NULL COMMENT '業務單號',
    creator          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '創建者',
    create_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
    updater          VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '更新者',
    update_time      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    deleted          BOOLEAN      NOT NULL DEFAULT FALSE COMMENT '是否刪除',
    tenant_id        BIGINT       NOT NULL DEFAULT 0 COMMENT '租戶編號',
    PRIMARY KEY (id),
    KEY idx_product_warehouse_tenant (product_id, warehouse_id, tenant_id, deleted) COMMENT '產品倉庫租戶索引',
    KEY idx_biz_tenant (biz_type, biz_id, tenant_id, deleted) COMMENT '業務類型租戶索引',
    KEY idx_biz_no_tenant (biz_no, tenant_id, deleted) COMMENT '業務單號租戶索引'
) COMMENT '產品庫存明細表';

